spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
  batch:
    job:
      # true는 Spring Boot 실행 시 등록되어 있는 Job들을 실행
      enabled: false
    jdbc:
      initialize-schema: always
      # JPA does not support custom isolation levels, so locks may not be taken when launching Jobs. To silence this warning, set 'spring.batch.jdbc.isolation-level-for-create' to 'default'.
      isolation-level-for-create: default

kakao:
  host: https://kapi.kakao.com
  token: ${ACCESS_TOKEN}

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb
  sql.init.mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10 # 지정된 개수만큼 쌓아뒀다가 쿼리를 보냄
logging:
  level:
    org.hibernate.type.descriptor.sql: trace # 바인딩되는 모든 파라미터를 출력
